### ISSUE TITLE
Result from different collection after interruption

### ISSUE THREAD

**Issue by lacostej** [mongoid/moped#239]
Interrupted a session on heroku console.

This resulted in very strange behavior from the client which started failing in various ways
- returning data from different collection, or mixing them
- failing intermittently until it started recovering

Using moped 1.5.0

```
irb(main):027:0* users=User.all.select { |u| stuck_user(u) }
[...]
52838dc76fddcaf32a0xxxxx,7,false,2013-11-21 12:20:03 UTC
^CIRB::Abort: abort then interrupt!
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/sockets/connectable.rb:46:in `call'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/sockets/connectable.rb:46:in `read'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/sockets/connectable.rb:46:in `block in read'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/sockets/connectable.rb:118:in `handle_socket_errors'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/sockets/connectable.rb:46:in `read'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/connection.rb:177:in `read_data'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/connection.rb:99:in `block in read'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/connection.rb:202:in `with_connection'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/connection.rb:97:in `read'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/protocol/query.rb:163:in `receive_replies'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/connection.rb:135:in `block in receive_replies'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/connection.rb:134:in `map'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/connection.rb:134:in `receive_replies'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/node.rb:584:in `block (2 levels) in flush'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/node.rb:150:in `ensure_connected'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/node.rb:582:in `block in flush'
... 21 levels...
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/cursor.rb:30:in `block in each'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/cursor.rb:30:in `each'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/cursor.rb:30:in `each'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/query.rb:76:in `each'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/query.rb:76:in `each'
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/contextual/mongo.rb:122:in `block in each'
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/contextual/mongo.rb:619:in `selecting'
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/contextual/mongo.rb:121:in `each'
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/contextual.rb:19:in `each'
    from (irb):27:in `select'
    from (irb):27
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'irb(main):028:0> 
irb(main):029:0* puts "#{users.count} stuck user(s)"^C
irb(main):029:0> User.find('5281e7f9914a19e4c4000010')
=> #<User _id: 528e053fb6217f40c2000044, user_type: :none, first_name: nil, last_name: nil, email: nil, last_session: nil, superadmin: false, owned_group_ids: nil, group_ids: nil, key: "LatestSysInfo", data: "{\"StackTrace\":\"N/A\",\"realtimeSinceStartup\":\"2.378000020980835\",.....}", user_id: "528c70bc96735ba53e00000c", game_id: "5114d642fb2212f7bd000002", updated_at: 2013-11-21 13:06:07 UTC, created_at: 2013-11-21 13:06:07 UTC>
```

Note the above result is NOT expected at all. It is a mix of 2 collections.

I re-run the right request just after 

```
irb(main):030:0> u=User.find('5281e7f9914a19e4c4000010')
=> #<User _id: 5281e7f9914a19e4c4000010, user_type: :student, first_name: "xxxxxxxxxx", last_name: "yyyyyyy", email: "", last_session: "RUTMIVUT", ....., owned_group_ids: nil, group_ids: [..........."], feideMeta: {"noSchools"=>false}>
irb(main):031:0> u=User.find('527ab086fd6737aa0d000017')
=> #<User _id: 5281e7f9914a19e4c4000010, user_type: :student, first_name: "xxxxxxxxxx", last_name: "yyyyyyy", email: "", last_session: "RUTMIVUT", ....., owned_group_ids: nil, group_ids: [..........."], feideMeta: {"noSchools"=>false}>
irb(main):032:0> u=User.find('5281e7f9914a19e4c4000010')
=> #<User _id: 527ab086fd6737aa0d000017, user_type: :student, first_name: "xxxxxxxxx", last_name: "ooooo", email: "", last_session: "4Z445JS9", ...., owned_group_ids: nil, group_ids: ["....."], feideMeta: {"noSchools"=>false}>
```

WTF I am getting wrong user now ?!

```
irb(main):033:0> u=User.find('5281e7f9914a19e4c4000010')
=> #<User _id: 5281e7f9914a19e4c4000010, user_type: :student, first_name: "xxxxxxxxxx", last_name: "yyyyyyy", email: "", last_session: "RUTMIVUT", ....., owned_group_ids: nil, group_ids: [..........."], feideMeta: {"noSchools"=>false}>
```

Now it's the right one. 
Now trying to get the one I received earlier:

```
irb(main):034:0> User.find('528e053fb6217f40c2000044')
Moped::Errors::OperationFailure: The operation: #<Moped::Protocol::Command
  @length=58
  @request_id=7884
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="admin.$cmd"
  @skip=0
  @limit=-1
  @selector={:ismaster=>1}
  @fields=nil>
failed with error nil
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/node.rb:99:in `block in command'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/node.rb:587:in `[]'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/node.rb:587:in `block (3 levels) in flush'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/node.rb:586:in `map'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/node.rb:586:in `block (2 levels) in flush'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/node.rb:150:in `ensure_connected'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/node.rb:582:in `block in flush'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/node.rb:597:in `logging'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/node.rb:581:in `flush'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/node.rb:570:in `process'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/node.rb:92:in `command'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/node.rb:407:in `refresh'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/cluster.rb:171:in `block in refresh'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/cluster.rb:185:in `each'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/cluster.rb:185:in `refresh'
    from /app/vendor/bundle/ruby/1.9.1/gems/moped-1.5.0/lib/moped/cluster.rb:135:in `nodes'
... 6 levels...
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/contextual/mongo.rb:122:in `block in each'
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/contextual/mongo.rb:619:in `selecting'
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/contextual/mongo.rb:121:in `each'
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/contextual.rb:19:in `each'
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/criterion/findable.rb:125:in `entries'
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/criterion/findable.rb:125:in `from_database'
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/criterion/findable.rb:93:in `multiple_from_map_or_db'
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/criterion/findable.rb:19:in `execute_or_raise'
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/criterion/findable.rb:40:in `find'
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/finders.rb:85:in `find'
    from (irb):34
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'irb(main):035:0> 
```

OK that failed badly. Let's try another one

```
irb(main):036:0* User.find('528e053fb6217f40c2000043')
=> #<User _id: 529867a6ff2f8a58d7000001, user_type: :none, first_name: nil, last_name: nil, email: nil, last_session: nil, superadmin: false, owned_group_ids: nil, group_ids: nil, ismaster: true, maxBsonObjectSize: 16777216, localTime: 2013-11-29 10:08:20 UTC, ok: 1.0>
```

WTF getting another object type again ? 

Retrying the previous one again!

```
irb(main):037:0> User.find('528e053fb6217f40c2000044')
Mongoid::Errors::DocumentNotFound: 
Problem:
  Document(s) not found for class User with id(s) 528e053fb6217f40c2000044.
Summary:
  When calling User.find with an id or array of ids, each parameter must match a document in the database or this error will be raised. The search was for the id(s): 528e053fb6217f40c2000044 ... (1 total) and the following ids were not found: 528e053fb6217f40c2000044.
Resolution:
  Search for an id that is in the database or set the Mongoid.raise_not_found_error configuration option to false, which will cause a nil to be returned instead of raising this error when searching for a single id, or only the matched documents when searching for multiples.
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/criteria.rb:464:in `check_for_missing_documents!'
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/criterion/findable.rb:20:in `execute_or_raise'
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/criterion/findable.rb:40:in `find'
    from /app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/finders.rb:85:in `find'
    from (irb):37
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

Different error?!!

What is going on ?

**Comment by msaspence** [comment]
I see a similar thing

I believe mine stems from incomplete reads of socket caused by Timeout::timeout being triggered
