### ISSUE TITLE
undefined method `each' for 0.5208793890141621:Float

### ISSUE THREAD

**Issue by aledalgrande** [mongoid/moped#253]
I have an issue similar to #164:

```
NoMethodError - undefined method `each' for 0.5208793890141621:Float:
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/atomic/modifiers.rb:121:in `add_operation'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/atomic/modifiers.rb:87:in `block in set'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/atomic/modifiers.rb:84:in `each_pair'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/atomic/modifiers.rb:84:in `set'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/atomic.rb:364:in `generate_atomic_updates'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/atomic.rb:134:in `block in atomic_updates'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/atomic.rb:132:in `each'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/atomic.rb:132:in `atomic_updates'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/persistence/operations.rb:145:in `init_updates'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/persistence/operations.rb:118:in `updates'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/persistence/operations/update.rb:46:in `block in persist'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/persistence/modification.rb:26:in `block (2 levels) in prepare'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-3.2.16/lib/active_support/callbacks.rb:403:in `_run__4472587378774119297__update__3763789925455941768__callbacks'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-3.2.16/lib/active_support/callbacks.rb:405:in `__run_callback'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-3.2.16/lib/active_support/callbacks.rb:385:in `_run_update_callbacks'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-3.2.16/lib/active_support/callbacks.rb:81:in `run_callbacks'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/callbacks.rb:130:in `run_callbacks'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/persistence/modification.rb:25:in `block in prepare'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-3.2.16/lib/active_support/callbacks.rb:403:in `_run__4472587378774119297__save__3763789925455941768__callbacks'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-3.2.16/lib/active_support/callbacks.rb:405:in `__run_callback'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-3.2.16/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-3.2.16/lib/active_support/callbacks.rb:81:in `run_callbacks'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/callbacks.rb:130:in `run_callbacks'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/persistence/modification.rb:24:in `prepare'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/persistence/operations/update.rb:45:in `persist'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/persistence.rb:150:in `update'
    /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mongoid-3.1.6/lib/mongoid/persistence.rb:87:in `save'
```

My models are:

```
class Point
  include Mongoid::Document

  field :x, type: Float
  field :y, type: Float

  embedded_in :line
end
```

```
class Line
  include Mongoid::Document

  field :visible, type: Boolean, default: true

  embeds_many :points
  belongs_to :layer
end
```

Cannot make any sense of it. The code that errors out works in specs, not on Sinatra.

**Comment by patricklehmann** [comment]
hey, could you fix this? i've got the same problem...
