### ISSUE TITLE
no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by sschepens** [mongoid/moped#290]
I'm getting a lot of this errors sin updating to moped2/mongoid4:

```
no implicit conversion of nil into String (TypeError)
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/connection/socket/tcp.rb:20:in `initialize'
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/connection/socket/tcp.rb:20:in `block in initialize'
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/connection/socket/connectable.rb:119:in `handle_socket_errors'
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/connection/socket/tcp.rb:20:in `initialize'
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/connection/socket/connectable.rb:145:in `new'
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/connection/socket/connectable.rb:145:in `block in connect'
/usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb:82:in `block in timeout'
/usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb:70:in `catch'
/usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb:70:in `timeout'
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/connection/socket/connectable.rb:144:in `connect'
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/connection.rb:52:in `connect'
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/node.rb:531:in `connect'
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/node.rb:179:in `block in ensure_connected'
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/node.rb:115:in `block in connection'
vendor/bundle/ruby/2.1.0/gems/connection_pool-2.0.0/lib/connection_pool.rb:58:in `with'
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/node.rb:114:in `connection'
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/node.rb:177:in `ensure_connected'
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/node.rb:589:in `block in flush'
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/node.rb:617:in `block in logging'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/notifications.rb:159:in `block in instrument'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.2/lib/active_support/notifications.rb:159:in `instrument'
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/instrumentable.rb:31:in `instrument'
vendor/bundle/ruby/2.1.0/gems/moped-2.0.0/lib/moped/node.rb:616:in `logging
```

**Comment by Elyasin** [comment]
I am having this issue at this very moment.

Anybody else ?

**Comment by arthurnn** [comment]
@Elyasin which version of moped are you using?
try using master and see if the error still persists.

**Comment by Elyasin** [comment]
Thanks for the quick answer.
From the logs: Moped 2.0.3
I will try your suggestion, however this happens on Heroku. On my local machine I never had that issue.
If you need any information let me know. In the meantime I will try your suggestion.

**Comment by Elyasin** [comment]
Yep, using master does not make a difference. Same error :-(

**Comment by arthurnn** [comment]
Maybe moped should give a better error message when the authentication credentials are `nil` or empty.
If anyone is interested to send a PR with that, I am willing to take a look.
thanks

**Comment by mnaqvi78** [comment]
i am having this issue..
how can this be resolved

in `open': no implicit conversion of nil into String (TypeError)
	from ex20a.rb:15:in `<main>'
