### ISSUE TITLE
NoMethodError - undefined method `each' for "53d00529486a1bcd28000075":Moped::BSON::ObjectId:

### ISSUE THREAD

**Issue by andresilveirah** [mongoid/moped#301]
Hi guys I already checked my logic but I don't see anything wrong, so I believe it could be a bug.

My models are:

``` ruby
class Payment
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia

  belongs_to :account, index: true
  field :deletion_reason
end

class Account
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActionView::Helpers::NumberHelper
  include PublicActivity::Common
  include ActionView::Helpers::DateHelper

  include Mongoid::Paranoia

  embeds_many :account_notes
  has_many :payments

  accepts_nested_attributes_for :payments
  accepts_nested_attributes_for :account_notes
end

class AccountNote < Note
  embedded_in :account
  TOPICS = ["billing", "client services issues", "class management info"]

  validates_presence_of :account
end

class Note
  include Mongoid::Document
  include Mongoid::Timestamps  

  belongs_to :user
  field :content, type: String
  field :topic, type: String
  field :date, type: Date, default: Date.current

  validates_presence_of :user, :topic, :content
end
```

The error occurs when executing the following code:

``` ruby
def destroy
    @payment = @account.payments.find(params[:id])
    @payment.update_attributes(deletion_reason: params[:payment][:deletion_reason])

    @payment.create_activity key: 'payment.deleted', owner: current_user, recipient: @account, params: {deletion_reason: @payment.deletion_reason}
    if @payment.destroy
       # THE EXCEPTION IS THROWN HERE ################
      @account.account_notes.create(topic: "billing", content: "Payment Deleted due to:\n#{@payment.deletion_reason}", account: @account, user_id: current_user.id, date: @payment.deleted_at)
      #################################################
      @account.update_balances_on(@payment.deleted_at.to_date)
    else
      @payment.activities.last.destroy
    end

    respond_to do |format|
      format.js
    end
  end
```

This is the stack trace:

```
NoMethodError - undefined method `each' for "53d00529486a1bcd28000075":Moped::BSON::ObjectId:
  mongoid (3.1.6) lib/mongoid/atomic/modifiers.rb:121:in `add_operation'
  mongoid (3.1.6) lib/mongoid/atomic/modifiers.rb:87:in `block in set'
  mongoid (3.1.6) lib/mongoid/atomic/modifiers.rb:84:in `set'
  mongoid (3.1.6) lib/mongoid/atomic.rb:364:in `generate_atomic_updates'
  mongoid (3.1.6) lib/mongoid/atomic.rb:134:in `block in atomic_updates'
  mongoid (3.1.6) lib/mongoid/atomic.rb:132:in `atomic_updates'
  mongoid (3.1.6) lib/mongoid/persistence/operations.rb:145:in `init_updates'
  mongoid (3.1.6) lib/mongoid/persistence/operations.rb:118:in `updates'
  mongoid (3.1.6) lib/mongoid/persistence/operations/update.rb:46:in `block in persist'
  mongoid (3.1.6) lib/mongoid/persistence/modification.rb:26:in `block (2 levels) in prepare'
  activesupport (3.2.16) lib/active_support/callbacks.rb:414:in `_run__1888542753040091012__update__2932193531082085051__callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.16) lib/active_support/callbacks.rb:385:in `_run_update_callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:81:in `run_callbacks'
  mongoid (3.1.6) lib/mongoid/callbacks.rb:130:in `run_callbacks'
  mongoid (3.1.6) lib/mongoid/persistence/modification.rb:25:in `block in prepare'
  activesupport (3.2.16) lib/active_support/callbacks.rb:414:in `_run__1888542753040091012__save__2932193531082085051__callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.16) lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:81:in `run_callbacks'
  mongoid (3.1.6) lib/mongoid/callbacks.rb:130:in `run_callbacks'
  mongoid (3.1.6) lib/mongoid/persistence/modification.rb:24:in `prepare'
  mongoid (3.1.6) lib/mongoid/persistence/operations/update.rb:45:in `persist'
  mongoid (3.1.6) lib/mongoid/persistence.rb:150:in `update'
  mongoid (3.1.6) lib/mongoid/persistence.rb:87:in `save'
  mongoid (3.1.6) lib/mongoid/relations/proxy.rb:143:in `method_missing'
  mongoid (3.1.6) lib/mongoid/relations/auto_save.rb:82:in `block (3 levels) in autosave'
  mongoid (3.1.6) lib/mongoid/relations/auto_save.rb:81:in `block (2 levels) in autosave'
  mongoid (3.1.6) lib/mongoid/relations/auto_save.rb:35:in `__autosaving__'
  mongoid (3.1.6) lib/mongoid/relations/auto_save.rb:78:in `block in autosave'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `_run__2983067559894985491__save__2932193531082085051__callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.16) lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:81:in `run_callbacks'
  mongoid (3.1.6) lib/mongoid/callbacks.rb:130:in `run_callbacks'
  mongoid (3.1.6) lib/mongoid/persistence/insertion.rb:23:in `prepare'
  mongoid (3.1.6) lib/mongoid/persistence/operations/embedded/insert.rb:32:in `persist'
  mongoid (3.1.6) lib/mongoid/persistence.rb:56:in `insert'
  mongoid (3.1.6) lib/mongoid/persistence.rb:85:in `save'
  mongoid (3.1.6) lib/mongoid/relations/many.rb:44:in `create'
  app/controllers/accounts/payments_controller.rb:56:in `destroy'
  actionpack (3.2.16) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.16) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.16) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.16) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.16) lib/active_support/callbacks.rb:469:in `_run__2531881480130901124__process_action__1173113247620882588__callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.16) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.16) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.16) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.16) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.16) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.16) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.16) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  newrelic_rpm (3.7.2.192) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:38:in `block in process_action'
  newrelic_rpm (3.7.2.192) lib/new_relic/agent/instrumentation/controller_instrumentation.rb:339:in `perform_action_with_newrelic_trace'
  newrelic_rpm (3.7.2.192) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:37:in `process_action'
  actionpack (3.2.16) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.16) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.16) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.16) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.16) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:608:in `call'
  newrelic_rpm (3.7.2.192) lib/new_relic/rack/error_collector.rb:55:in `call'
  newrelic_rpm (3.7.2.192) lib/new_relic/rack/agent_hooks.rb:32:in `call'
  newrelic_rpm (3.7.2.192) lib/new_relic/rack/browser_monitoring.rb:27:in `call'
  newrelic_rpm (3.7.2.192) lib/new_relic/rack/developer_mode.rb:45:in `call'
  mongoid (3.1.6) lib/rack/mongoid/middleware/identity_map.rb:34:in `block in call'
  mongoid (3.1.6) lib/mongoid/unit_of_work.rb:39:in `unit_of_work'
  mongoid (3.1.6) lib/rack/mongoid/middleware/identity_map.rb:34:in `call'
  warden (1.2.1) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.1) lib/warden/manager.rb:34:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `_run__2010804792476588076__call__2932193531082085051__callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.16) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.16) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  better_errors (0.9.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (0.9.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (0.9.0) lib/better_errors/middleware.rb:56:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.16) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.16) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.16) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.16) lib/rails/rack/logger.rb:16:in `call'
  quiet_assets (1.0.2) lib/quiet_assets.rb:18:in `call_with_quiet_assets'
  actionpack (3.2.16) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.16) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/static.rb:63:in `call'
  railties (3.2.16) lib/rails/engine.rb:484:in `call'
  railties (3.2.16) lib/rails/application.rb:231:in `call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.16) lib/rails/rack/log_tailer.rb:17:in `call'
  thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
  thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
  thin (1.5.1) lib/thin/connection.rb:54:in `process'
  thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
  thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
  thin (1.5.1) lib/thin/server.rb:159:in `start'
  rack (1.4.5) lib/rack/handler/thin.rb:13:in `run'
  rack (1.4.5) lib/rack/server.rb:268:in `start'
  railties (3.2.16) lib/rails/commands/server.rb:70:in `start'
  railties (3.2.16) lib/rails/commands.rb:55:in `block in <top (required)>'
  railties (3.2.16) lib/rails/commands.rb:50:in `<top (required)>'
  script/rails:6:in `<main>'
  script/rails:0:in `<main>'
```

By the way, the id in the exception message, "53d00529486a1bcd28000075" , is the id of the AccountNote object, that got created.

Please let me know if I can provide more information.

**Comment by msaspence** [comment]
I also had this problem, a more specific warning would have been useful. If not for this issue, god knows how long I would have been going around in circles.

**Comment by ajsharp** [comment]
I see similar errors, though I see them with embedded models and ruby `Time` objects on the `created_at` property.

**Comment by ajsharp** [comment]
I was able to fix mine by removing one of my relations.
