### ISSUE TITLE
"key not found" error pops up sometimes after first query when Rails 4 server starts

### ISSUE THREAD

**Issue by markslemko** [mongoid/moped#305]
I'm not sure where or what this bug is coming from, but it happens pretty often. I'm wondering, has anyone seen this and know what is going on and how to fix it?

examples:
- A KeyError occurred in mycontroller#create:
  - key not found: ">"

the line of code that triggers the strangeness is like this:
User.find(params[:user_id])
or 
Game.find(params[:game_id'])
where params[:user_id] = "5099e92f2008726e53000001"

Other examples:
- A KeyError occurred in mycontroller#create:
  - key not found: "\"
- A KeyError occurred in mycontroller#create:
  - key not found: "w"
- A KeyError occurred in mycontroller#index:
- key not found: "P"

Any thoughts appreciated

**Comment by asiazhang** [comment]
same here.

error: key not found: "a"

backtrace:

```
"/root/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bson-2.3.0/lib/bson/registry.rb:43:in `fetch'", 
"/root/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bson-2.3.0/lib/bson/registry.rb:43:in `get'", 
"/root/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bson-2.3.0/lib/bson/hash.rb:79:in `from_bson'", 
"/root/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/connection_pool-2.0.0/lib/connection_pool.rb:58:in `with'", 
```

**Comment by jeremyhaile** [comment]
I'm getting this over and over on mongoid 4.0.2

**Comment by arthurnn** [comment]
Can someone write an isolated app or test file, so I can simulate this error locally?
thanks
