### ISSUE TITLE
undefined method __bson_dump__

### ISSUE THREAD

**Issue by tonyto** [mongoid/moped#55]
I'm getting issues with saving a Mongoid object through the moped driver.

My model

``` ruby
class Task
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
end
```

After I create a new session, and try to insert a document into the collection:

``` ruby
session = Moped::Session.new([ "127.0.0.1:27017" ])
session.use "echo_test"
session[:task].insert(Task.new)
```

I get the following stack trace....

```
NoMethodError: undefined method `__bson_dump__' for #<Task:0x00000102ca6ba8>
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/mongoid-3.0.2/lib/mongoid/attributes.rb:225:in `method_missing'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/bson/document.rb:11:in `serialize'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/protocol/message.rb:129:in `block in serialize_documents'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/protocol/message.rb:128:in `each'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/protocol/message.rb:128:in `serialize_documents'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/protocol/message.rb:287:in `serialize'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/connection.rb:137:in `block in write'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/connection.rb:135:in `each'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/connection.rb:135:in `write'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/node.rb:518:in `block (2 levels) in flush'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/node.rb:113:in `ensure_connected'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/node.rb:517:in `block in flush'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/node.rb:532:in `logging'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/node.rb:516:in `flush'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/node.rb:505:in `process'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/node.rb:228:in `insert'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/session/context.rb:63:in `block in insert'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/session/context.rb:109:in `block in with_node'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/cluster.rb:139:in `block in with_primary'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/node.rb:158:in `ensure_primary'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/cluster.rb:138:in `with_primary'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/session/context.rb:108:in `with_node'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/session/context.rb:56:in `insert'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/collection.rb:88:in `block in insert'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/session.rb:264:in `with'
    from /Users/.rvm/gems/ruby-1.9.3-p194@list/gems/moped-1.1.5/lib/moped/collection.rb:87:in `insert'
```

I tailed through some of the closed issues and I can confirm that the object id is an Moped::BSON::ObjectId.

I'm using MongoDB (2.0.7), mongoid (3.0.2), moped (1.1.5)

Could you shed some light?

**Comment by klaus-trabalhando** [comment]
I had this problem with **DateTime** object and I did this to fix it (an initializer file with anyone name):

```
class DateTime
  def __bson_dump__(x,z)
    self.to_time.__bson_dump__(x, z)
  end
end
```
